#!/bin/sh
#

set -e

export GOPATH=/root/go
PATH=/bin:/usr/bin:/sbin:/usr/sbin:$GOPATH/bin
NAME=apache_exporter
DESC="apache_exporter servlet engine"


do_start() {
  apache_exporter &
}

do_stop() {
  pkill -9 apache_exporter
}

case "$1" in
  start)
    do_start
    ;;
  stop)
    do_stop
    ;;
  *)
    log_success_msg "Usage: $0 {start|stop}"
    exit 1
    ;;
esac

exit 0
