version: '3.1'

services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./my-prometheus.yml:/etc/prometheus/prometheus.yml
  apache:
    image: apache
    build: . 
    container_name: apache
    ports:
      - "80:80"
    volumes:
      - ./httpd-tomcat.conf:/usr/local/apache/conf/httpd.conf 
  tomcat8:
    image: dagman62/tomcat8
    container_name: tomcat8
    ports:
      - "8080:8080"

